/*
 * Copyright (c) 2020 Nuvoton Technology Corporation.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_ESPI_NPCM4XX_ESPI_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_ESPI_NPCM4XX_ESPI_H_

/* eSPI VW Master to Slave Register Index */
#define NPCM4XX_VWEVMS0 0
#define NPCM4XX_VWEVMS1 1
#define NPCM4XX_VWEVMS2 2
#define NPCM4XX_VWEVMS3 3
#define NPCM4XX_VWEVMS4 4
#define NPCM4XX_VWEVMS5 5
#define NPCM4XX_VWEVMS6 6
#define NPCM4XX_VWEVMS7 7
#define NPCM4XX_VWEVMS8 8
#define NPCM4XX_VWEVMS9 9

/* eSPI VW Slave to Master Register Index */
#define NPCM4XX_VWEVSM0 0
#define NPCM4XX_VWEVSM1 1
#define NPCM4XX_VWEVSM2 2
#define NPCM4XX_VWEVSM3 3
#define NPCM4XX_VWEVSM4 4
#define NPCM4XX_VWEVSM5 5
#define NPCM4XX_VWEVSM6 6
#define NPCM4XX_VWEVSM7 7
#define NPCM4XX_VWEVSM8 8
#define NPCM4XX_VWEVSM9 9
#define NPCM4XX_VWEVSM10 10
#define NPCM4XX_VWEVSM11 11

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_ESPI_NPCM4XX_ESPI_H_ */
